#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

[ -c /dev/console ] || mknod -m 600 /dev/console c 5 1
[ -c /dev/null ] || mknod -m 666 /dev/null c 1 3
[ -c /dev/tty ] || mknod -m 666 /dev/tty c 5 0
[ -c /dev/tty0 ] || mknod -m 666 /dev/tty0 c 4 0
[ -c /dev/ttyS0 ] || mknod -m 600 /dev/ttyS0 c 4 64
[ -c /dev/ptmx ] || mknod -m 666 /dev/ptmx c 5 2

exec >/dev/ttyS0 2>&1 </dev/ttyS0

ip addr add 10.0.2.15/24 dev eth0
ip link set eth0 up
ip route add default via 10.0.2.2
echo "nameserver 8.8.8.8" > /etc/resolv.conf


echo "Welcome to smtdfcOS"
exec setsid cttyhack sh
exec setsid /bin/sh -i
