#!/bin/sh
mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys

exec >/dev/console 2>&1
echo ">> INIT script started"
ls /

echo -e "\n🔥 Welcome to smtdfcOS 🔥"
exec /bin/sh
