#!/bin/busybox sh

# Mount các thư mục ảo cần thiết cho shell
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev || mknod -m 622 /dev/console c 5 1

# In ra chút cho vui
echo "[+] Welcome to smtdfcOS 🤡"
echo "[+] Starting BusyBox shell..."

# Chạy shell
exec /bin/busybox sh
